#!/usr/bin/env ruby

require 'scaltainer'

begin
  configfile, statefile, logger, wait, orchestrator = Scaltainer::Command.parse ARGV
  Scaltainer::Runner.new configfile, statefile, logger, wait, orchestrator
rescue => e
  $stderr.puts e.message
  $stderr.puts e.backtrace
  exit 1
end