name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install bundler
        shell: bash
        # The bundler version used must match the one in the repo's gemspec
        run: gem install bundler:2.2.19
      - name: Bundle dependencies
        shell: bash
        run: bundle
      - name: Release gem
        shell: bash
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: ./publish.sh
